# Generated by Django 3.2.10 on 2023-12-05 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
