# Generated by Django 3.2.10 on 2023-12-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='available',
        ),
        migrations.AddField(
            model_name='movie',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
    ]
