# Generated by Django 3.2.10 on 2023-12-05 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20231206_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='available',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rented_by',
        ),
    ]
